version: '3.8'

services:
  backend:
    build: .
    container_name: ecossistema_backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - API_KEY=iUCrkaBILIhhAI_2qB1gVlUgkpo-pbXtAcYB9n7xv3o
