name=scMQTTLib
version=1.0.4
author=Silas Torres Rocha
maintainer=Silas Torres Rocha
sentence=Biblioteca simples para conectar ESP8266/ESP32 a um broker MQTT persoanalizado com Rate Limiting nativo e roteamento automático de tópicos.
paragraph=Esta biblioteca fornece uma interface abstraída sobre a PubSubClient. Ela facilita a conexão ao servidor (padrão ou customizado), envio de telemetria em formato JSON de maneira simplificada, e a assinatura para recebimento de comandos, enquanto garante um limite seguro da taxa de envio e validação das conexões.
category=Communication
url=https://github.com/Depois_Coloco_Isso
architectures=esp8266,esp32
includes=scMQTTLib.h
depends=PubSubClient,ArduinoJson
